### ISSUE TITLE
Create list of tasks that must be completed for working project

### ISSUE THREAD

**Issue by tomeon** [BaxterStockman/cloudendar#2]
@looneyka 
@clampitc 

This is absolutely critical.  We need to have a solid understanding of what remains to be done in order to complete the project -- more than that, we need to have a _record_ of what needs to be done.  So, **please take some time today to write down what remains to be done**, focusing especially on the your assigned part of the project "trilogy" (CLI, webapp, back).

When this is done, **please send me your list**.  I will assemble them into milestones and issues posted here in our GitHub repo.  From now on our repo will be the definitive oracle of project tasks, due dates, and progress.  It is my hope that providing this structure will facilitate more fluid and meaningful communication, and smoother progress on our project.  Thanks!

**Comment by clampitc** [comment]
OK, so here is what I know needs to get done but I am not sure from your
standpoints where you are so I will take a guess at it.

web site that:
       1) displays basic login
       2) screen allowing user to pick dates and retrieve from DB and
Calendar free slots from both for users requested
       3) some way to interact with and maybe display the Google calendar

CLI:
     1) some way allowing user to pick dates and retrieve from DB and
Calendar free slots from both for users requested
     2) some way to interact with and maybe display the Google calendar

DB may need additional changes as we modify design

ScreenScraping needs to successfully scrape all 7K+ courses with all
relevant sections under each link and record them in DB

Also, how are we going to do a video. Should we do 3 pieces and submit all
3 to Teach by midnight on Monday? What software are you two using?
