### ISSUE TITLE
Webapp - implement searching of usernames in database

### ISSUE THREAD

**Issue by tomeon** [BaxterStockman/cloudendar#6]
Once the database is complete, we should be able to pull and display username data as the user searches for usernames in the search form.  This should be accomplished with the Whoose text search module.

Once search results are displayed, users should be able to add the usernames of interest to the list that will be used to generate free/busy time slots.

**Comment by clampitc** [comment]
Matt--

I assume these are coming from you but I do not know if I can reply to
these or not. If you get this can you reply so I know that I can send to
you. I assume this is through GitHub but not sure? also, I am taking a
midterm but looks like you made some progress and we have till tomorrow
night. I have to take my midterm tonight, finish my selfcheck, and get my
final part of my lab done so I may be working on the video late tonight
tomorrow. Let me know if you get this and thus I can reply in this manner
to these emails or if I should send through normal email.

Cheers!
Charles

**Comment by tomeon** [comment]
Hi Charles,  

You're getting automatic notifications of new issues posted in our repo; you can respond via email if you like, but probably the best thing to do is post replies in the issue threads, like you did the other day.  

Good luck on your midterm!  If you could send me your progress for the week, I'd really appreciate it.  Also, do you know what's up with Kayla?  I haven't head from her in a while, and she hasn't committed anything to our repo in about 2 weeks.  Maybe she's at Coachella or something?
